mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views
from polls import views

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('signup/', views.signup, name='signup'),
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='user_logout'),
    path('', RedirectView.as_view(url='/polls/')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('results/<int:question_id>/', views.results, name='results'),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User


class Question(models.Model):
    """
    Model representing a poll question.
    """
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    end_date = models.DateTimeField("end date", null=True, blank=True)

    def __str__(self):
        """
        String representation of the question.
        """
        return self.question_text

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        """
        Check if the question was published recently.
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def is_published(self):
        """
        Check if the question is published.
        """
        now = timezone.now()
        return now >= self.pub_date

    def can_vote(self):
        """
        Returns True if the question can be voted on, False otherwise.
        """
        now = timezone.now()
        if self.end_date is None:
            return self.pub_date <= now
        return self.pub_date <= now <= self.end_date


class Choice(models.Model):
    """
    Model representing a choice for a poll question.
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    def __str__(self):
        """
        String representation of the choice.
        """
        return self.choice_text

    @property
    def votes(self):
        return Vote.objects.filter(choice=self).count()


class Vote(models.Model):
    """Records a Vote of a Choice by a User"""
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def str(self):
        return str(self.user) + " voted for " + str(self.choice)

results/models.py
from django.db import models

# Create your models here.

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required  # Import the login_required decorator
from django.contrib.auth import logout  # Import the logout function
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

from .models import Choice, Question, Vote


def index(request):
    """
    Displays a list of the latest five published questions.

    Returns:
        Rendered HTML page displaying the latest questions.
    """
    latest_question_list = Question.objects.filter(pub_date__lte=timezone.now())\
        .order_by('-pub_date')
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)


def detail(request, pk):
    """
    Displays the details of a specific question.

    Args:
        request: The HTTP request object.
        pk: The ID of the question to display.

    Returns:
        Rendered HTML page displaying the question details.
    """
    # question = get_object_or_404(Question, pk=pk)
    # return render(request, "polls/detail.html", {"question": question})

    try:
        question = Question.objects.get(pk=pk)
    except Question.DoesNotExist:
        # If the question does not exist, you can redirect to another page.
        messages.error(request, "The poll you requested does not exist.")
        return redirect('polls:index')  # Redirect to the polls index page

        # Check if voting is allowed for this question
    if not question.can_vote():
        messages.error(request, "Voting is not allowed for this poll.")
        return redirect('polls:index')

    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    """
    Displays the results of a specific question.

    Args:
        request: The HTTP request object.
        question_id: The ID of the question to display results for.

    Returns:
        Rendered HTML page displaying the question results.
    """
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last ten published questions (not including those set to be
        published in the future and questions with end_date in the past).
        """
        now = timezone.now()
        return Question.objects.filter(pub_date__lte=now).order_by("-pub_date")[:12]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now(), end_date__gte=timezone.now())

    def get(self, request, *args, **kwargs):
        """
        Checks if the question is available to vote, and redirects if not.

        Args:
            request: The HTTP request object.

        Returns:
            Rendered HTML page displaying the question details or a 404 response.
        """
        question = get_object_or_404(Question, pk=kwargs['pk'])
        if not question.can_vote():
            messages.error(request, "Voting is not allowed for this poll.")
            return redirect('polls:index')
        return render(request, 'polls/detail.html', {'question': question})


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


@login_required
def vote(request, question_id):
    """Vote for one of the answers to a question."""

    # question = get_object_or_404(Question, pk=question_id)

    # Check if the question exists
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        messages.error(request, "The poll you requested does not exist.")
        return redirect('polls:index')  # Redirect to the polls index page

    # Check if voting is allowed for this question
    if not question.can_vote():
        messages.error(request, "Voting for this question is not allowed.")
        return redirect('polls:index')

    # Render 'detail.html' template with 'question' for GET requests.
    if request.method == "GET":
        return render(request, 'polls/detail.html', {'question': question})

    try:
        # Get the selected choice from the POST data
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Re-show the voting form for the question if choice is not selected
        messages.error(request, "You didn't select a choice.")
        return render(request, 'polls/detail.html', {'question': question})

    recently_user = request.user

    try:
        # Check if the user has already voted for this choice
        vote = Vote.objects.get(user=recently_user, choice__question=question)
        vote.choice = selected_choice
    except Vote.DoesNotExist:
        # Create a new vote for the selected choice and user
        vote = Vote.objects.create(choice=selected_choice, user=recently_user)

    vote.save()
    messages.success(request, f"Your vote for {selected_choice} has been saved.")

    # Redirect to the results page for the question
    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


def signup(request):
    """Register a new user."""
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # get named fields from the form data
            username = form.cleaned_data.get('username')
            # password input field is named 'password1'
            raw_passwd = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_passwd)
            login(request, user)
            return redirect('polls:index')
    else:
        # create a user form and display it on the signup page
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


@login_required
def user_logout(request):
    """Logout the user."""
    logout(request)
    messages.success(request, "You have been logged out successfully.")
    return redirect('polls:index')

results/views.py
from django.shortcuts import render

# Create your views here.

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ question.question_text }}</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #D0E7D2;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        .container {
            background-color: #fff;
            max-width: 600px;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            display: flex;
            flex-direction: column;
            margin-bottom: 40px;
        }

        h1 {
            text-align: center;
            color: #004225;
        }

        .messages-container {
            background-color: #F8C4B4;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 5px;
        }


        .messages-text {
            font-size: 16px;
            color: darkred;
            font-weight: bold;
        }

        form {
            margin-top: 20px;
            width: 100%;
        }

        .choice-container {
            margin: 15px 0;
            display: flex;
            align-items: center;
        }

        .choice-container input[type="radio"] {
            margin-right: 20px;
        }

        .vote-button {
            background-color: #004225;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 18px;
            width: 100%;
            align-self: center;
            transition: background-color 0.3s ease;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        .vote-button:hover {
            background-color: #004225;
        }

        input[type="hidden"] {
            display: none;
        }

        .back-to-list {
            font-size: larger;
            text-align: center;
            margin-top: 20px;
            text-decoration: none;
            color: #004225;
            font-weight: bold;
            transition: color 0.3s ease;
        }

        .back-to-list:hover {
            color: #618264;
        }

    </style>
</head>
<body>
    <div class="container">
        <h1>{{ question.question_text }}</h1>
        <!-- Display the confirmation message if it exists -->
        {% if messages %}
            {% for message in messages %}
                <div class="messages-container {% if message.tags %}messages-{{ message.tags }}{% endif %}">
                    <p class="messages-text">{{ message }}</p>
                </div>
            {% endfor %}
        {% endif %}

        <form id="vote-form" method="post" action="{% url 'polls:vote' question.id %}">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <div class="choice-container">
                    <input type="radio" name="choice" id="choice{{ choice.id }}" value="{{ choice.id }}">
                    <label for="choice{{ choice.id }}">{{ choice.choice_text }}</label>
                </div>
            {% endfor %}
            <input type="submit" value="Vote" class="vote-button">
        </form>
    </div>
    <a href="{% url 'polls:index' %}" class="back-to-list">Back to List of Polls</a>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KU Polls</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #D0E7D2;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        .container {
            background-color: #fff;
            max-width: 800px;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #004225;
        }

        .messages-container {
            background-color: #F8C4B4;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 5px;
        }


        .messages-text {
            font-size: 16px;
            color: darkred;
            font-weight: bold;
        }

        .user-actions {
            text-align: center;
            margin-top: 30px;
            margin-bottom: 30px;
        }

        .user-actions a {
            text-decoration: none;
            color: #618264;
            margin: 0 10px;
            transition: color 0.3s ease;
        }

        .user-actions a:hover {
            color: #D0E7D2;
        }

        .poll-list {
            list-style-type: none;
            padding: 0;
        }

        .poll-item {
            background-color: #D0E7D2;
            border: 1px solid #ccc;
            border-radius: 10px;
            padding: 20px;
            margin: 20px 0;
        }

        .poll-item .poll-link {
            text-decoration: none;
            color: #004225;
            font-weight: bold;
            transition: color 0.3s ease;
        }

        .poll-item .poll-link:hover {
            color: #618264;
        }

        .poll-title {
            display: flex;
            flex-direction: column;
            font-weight: bold;
            color: #004225;
            font-size: 18px;
        }

        .poll-description {
            display: flex;
            justify-content: flex-end;
            margin-top: 14px;
        }

        .no-polls {
            text-align: center;
            color: #777;
        }

        .publish-date {
            font-size: 14px;
            color: #618264;
            margin-top: 10px;
        }

        .vote-button {
            color: #FFFFFF;
            background-color: #004225;
            padding: 8px 16px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
            font-size: 16px;
            text-decoration: none;
        }

        .vote-button:hover {
            color: #004225;
            background-color: #FFFFFF;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>Welcome to KU Polls</h1>
        <!-- Display the confirmation message if it exists -->
        {% if messages %}
            {% for message in messages %}
                <div class="messages-container {% if message.tags %}messages-{{ message.tags }}{% endif %}">
                    <p class="messages-text">{{ message }}</p>
                </div>
            {% endfor %}
        {% endif %}

        <div class="user-actions">
            {% if user.is_authenticated %}
                {% if user.is_staff %}
                    <a href="{% url 'admin:index' %}" target="_blank">Administration</a>
                {% endif %}
                <a href="{% url 'user_logout' %}">Logout</a>
                <span>Welcome back {{ user.username }}!</span>
            {% else %}
                <a href="{% url 'login' %}?next={{ request.path }}">Login</a>
                <span> </span>
                <a href="{% url 'signup' %}">Signup</a>
            {% endif %}
        </div>

        {% if latest_question_list %}
        <ul class="poll-list">
            {% for question in latest_question_list %}
                <li class="poll-item">
                    <div class="poll-title">
                        <span>
                            {{ question.question_text }} (<a href="{% url 'polls:results' question.id %}" class="poll-link">Results</a>)
                        </span>
                        <small class="publish-date">
                            Published Date: {{ question.pub_date|date:"F d, Y" }}
                            {% if question.end_date %}
                                <br>End Date: {{ question.end_date|date:"F d, Y" }}
                            {% endif %}
                            <br>Status: <span style="color: {% if question.can_vote %}green{% else %}red{% endif %};">
                            {% if question.can_vote %}
                                Open
                            {% else %}
                                Closed
                            {% endif %}
                            </span>
                        </small>
                    </div>
                    <div class="poll-description">
                        <a href="{% url 'polls:vote' question.id %}" class="vote-button">Vote</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p class="no-polls">No polls are available.</p>
    {% endif %}
</div>
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results for: {{ question.question_text }}</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #D0E7D2;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        .container {
            background-color: #fff;
            max-width: 600px;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #004225;
            margin-bottom: 20px;
        }

        .confirmation-container {
            background-color: #d4edda;
            color: #004225;
            border: 1px solid #c3e6cb;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 20px;
        }

        .confirmation-message {
            font-size: 16px;
        }

        .result-list {
            list-style: none;
            padding: 0;
        }

        .result-list li {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
        }

        .choice-container {
            flex: 1;
            background-color: #f8f9fa;
            padding: 10px;
            margin-top: 18px;
            margin-bottom: 18px;
            border-radius: 5px;
        }

        .choice-text {
            font-size: 16px;
            color: #004225;
        }

        .vote-count {
            font-size: 16px;
            color:#004225;
        }

        .back-to-list {
            display: block;
            text-align: center;
            text-decoration: none;
            background-color: #004225;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 18px;
            margin-top: 20px;
            transition: background-color 0.3s ease;
        }

        .back-to-list:hover {
            background-color: #618264;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Results for: {{ question.question_text }}</h1>
        <!-- Display the confirmation message if it exists -->
        {% if messages %}
            <div class="confirmation-container">
                <p class="confirmation-message">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                </p>
            </div>
        {% endif %}
        <ul class="result-list">
            {% for choice in question.choice_set.all %}
                <li class="choice-container">
                    <div>
                        <span class="choice-text">{{ choice.choice_text }}</span>
                    </div>
                    <span class="vote-count">{{ choice.votes }} vote{{ choice.votes|pluralize }}</span>
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'polls:index' %}" class="back-to-list">Back to List of Polls</a>
    </div>
</body>
</html>